pangpang-study/algorithm-coding-test-study

jhy/210930/돌림판 (Small).py, jhy/210930/빗물.py, jhy/210930/쿠키의 신체 측정.py
갈길이 한참 멀다는 생각이 들었다. 속도가 날 수 있게 더 많이 문제를 봐야 할듯.
이 문제는 난이도도 매우 낮다고 생각하고 구상은 쉽게 되었으나, 내가 구현력이 너무 부족해 애를 많이 먹었던 문제다.
`1. 머리는 심장 위로 길이 1`
`2. 허리, 팔, 다리 길이 1 이상, 너비 1`
`3. 5 <= n <= 1000`
`4. 1 <=i, j <= n`
쿠키 신체 주어질 때, 심장 위치, 왼팔, 오른팔, 허리, 왼다리, 오른다리 길이 순으로 출력. 
1. 첫 '*" 만날 때까지 탐색 후(머리 탐색) 한 칸 아래가 심장 좌표로 등록.
2. 심장 기준 왼쪽, 오른쪽, 아래로 각각 진행해 왼팔, 오른팔, 허리 길이 구하기.
(팔의 경우, 인덱스를 벗어나는 범위에 대한 처리를 해줘야 함.)
3. 심장 좌표 기준, y축에 허리 길이 + 1만큼 더해준 위치에서, 양쪽으로 왼다리, 오른 다리 길이도 같은 방식으로 구하기.
(다리의 경우도 팔과 같이 인덱스를 벗어나는 범위에 대해 처리를 해줌.)
4. 심장 좌표와 구한 길이들 출력
이 문제의 포인트는 완전 구현으로써 실수 없이, 예외처리를 잘 해주면서 꼼꼼한 구현을 해낼 수 있는 능력이 있느냐에 대한 부분이었던 것 같다.
2차원 배열을 잘 쓰지 못하면(좌표 구하기, 좌표 활용하기 등) 힘들 문제인 것 같으며, 본인이 그렇게 느꼈다.
이 문제는 생김새가 쉬워보였고, 실제 쉬운편에 속하는 문제 유형일 거 같다고는 생각하지만 내 기준에서는 생각이 바로 정리가 되지는 않았던 문제이다.
`1. 2차원 세계 세로 길이 H와 가로 길이 W (1 <= H, W <= 500)`
`2. …
=> [210930] 정하영

yhg/Labminsang.py, yhg/cookierun.py, yhg/dolim.py, yhg/magicShark.py, yhg/rain.py
입력 받는 쿠키의 모양중에서 제일 먼저 만나게 되는것은 머리다.
따라서 머리의 위치를 찾고나서 바로 아래에는 심장이 있으므로 그 좌표를 저장 한다.
심장을 찾고나면 왼쪽으로 * 이 안나올 때까지 탐색하고 그 길이를 저장한다.
오른쪽 팔도 동일한 방법으로 저장한다.
허리도 위와 같이 아래로 탐색하고 * 끝나는 위치를 허리의 끝으로 저장한다.
다리는 허리의 끝나는 기준 왼쪽아래와 오른쪽 아래로 한칸 이동후 아래로 탐색하고 
심장의 위치와 각 부위의 길이를 출력해준다.
입력받은 돌림판을 queue에 넣는다.
이때 1번시행한 후 k-1 번 시행하므로 결국 k 번 진행한다는 말이다.
k번을 진행할때 현재 칠해져있는 돌림판을 기준으로 새로운 돌림판에 칠한다고 생각하고 진행하였다.
이때 돌림판의 색깔을 queue에 넣은 이유는 다음과 같이 진행하기 위해서다.
1. queue에서 popleft를 한 색깔은 가운대로 위치시킨다.
2. 한번더 popleft를 한 색깔은 오른쪽으로 위치시킨다.
3. pop을 한 색깔은 왼쪽에 위치시킨다.
4. 주어진 조건에 따라 새로운 판에 색깔을 칠한다.
5. 돌림판의 다음 색깔을 확인하기 위해서 돌림판이 돌아간것 처럼 데이터를 재배치한다.
6. 위의 과정을 돌림판 색깔의 개수만큼 반복한다.
7. 한번 끝나면 새로 칠한 판을 기준으로 위의 과정을 반복한다.
위의 과정을 진행한 그림은 아래와 같다.
이후에 색깔의 개수를 세어 출력해주면 된다.
입력을 받을 때 에어컨의 위치를 미리 좌표로 받고, 앉을 위치에 바로 추가한다.
이후에 에어컨의 개수만큼 바람의 방향인 상하좌우로 에어컨 마다 한번씩 …
=> [210930] 유현근

nyc/211026/baekjoon_1051_digit_square.java, nyc/211026/baekjoon_19583_cyber.java, nyc/211026/baekjoon_8911_turtle.java
`파이썬이었다면 정말 쉬웠을 문제들, 자바로 푸니 아직 손에 덜익었다~`
이 문제는 간단한 구현 문제이다. 그래서 파이썬으론 쉽게 풀 수 있을 것 같아서 자바로 구현해보았다.
1. F, B 만나면 현재 바라보는 방향 기준으로 앞으로 움직이고 뒤로 움직임
2. L, R 만나면 turn 함수 호출
1. turn 함수: 방향만 바꿔줌.
3. x, y 좌표의 최대, 최소값을 계속 업데이트
이 문제의 포인트는 실수하지말자. 자바로 `String` 다루는걸 더 연습해야겠다.
이 문제는 문자열 잘 처리 할 수 있는지 물어보는 문제이다. 문자열로 시간 비교해서 문제에서 주어지는 조건대로 해시 자료구조를 이용해서 개강총회 참석 여부를 구하면 된다.
1. S, E, Q 기본 입력 받고, 해시 자료구조 선언
2. 한 줄 씩 입력을 받으면서.
1. 채팅이 총회 시작시간보다 같거나 전이다. -> 해시에 이름 추가
2. 채팅이 총회 끝 시간과 같거나 이후, 스트리밍과 같거나 이전, 해시에 이름 있으면 -> 카운트 += 1, 해시에서 제거
3. 카운트 출력
이 문제의 포인트는 문자열을 인트로 바꿔서 초단위로 풀기. 1번 문제 풀고 String 연습하고 싶었는데 이런 문제가 딱. 나이스
이 문제는 가장 큰 정사각형부터 되는지 판별해보고 하나씩 줄여나가면서 풀면 되는 문제이다. 보드의 크기가 최대 50밖에 안되므로 그냥 풀면 된다.
1. 3중 포문
1. `len = min(N, M)`
2. `n, m` 순회하며 네 꼭짓점`(i,j)(i+len, j)(i, j+len)(i+len, j+len)`이 같은지 비교. 같다면 -> 종료
3. …
=> [211026] 남윤창

yhw/211026/거북이.java, yhw/211026/사이버개강총회.java, yhw/211026/숫자정사각형.java
크게 어렵지 않았다! 구현력이 조금은 상승한듯?
f,b에서는 거북이가 움직이고, l,r에서는 바라보고 있는 방향을 바꾼다
이때 거북이의 움직인 위치만큼에서의 최대 직사각형 넓이를 구하는 문제
왼쪽으로 거북이가 이동한 최대 좌표를 저장
오른쪽으로 거북이가 이동한 최대 좌표를 저장
왼쪽으로 거북이가 이동한 최소 좌표를 저장
오른쪽으로 거북이가 이동한 최소 좌표를 저장
이 네가지의 경우를 다 해서 나온 최종값을 곱해주면 최대가 된다.
방향을 바꾸어 이동시킬수 있는가?를 묻는 브루트 포스와 간단한 수학 문제였다고 생각한다.
이 문제는 상당히 더러운 문제였다. 해시를 이용해서 문자열을 잘 분리할 수 있는지를 보는 문제였음.
시작시간은 그냥 시작 시보다 작거나 같고, 분보다 같거나 작으면 방명록 hash에 담아준다.
퇴장시간과 스트리밍 종료시간을 계산해서 그 사이에 채팅기록이 있는 놈들이 있다면
방명록에서 빼줌과 동시에, 결과값 증가
없다면
다음 로그로 넘어가게 해줌
이 문제의 포인트는 해시를 얼마나 잘 다룰 수 있는지, 문자열을 자를 수 있는지를 보는 문제였음
이 문제는 각 꼭지점이 같은 정사각형의 최대 넓이를 구하는 문제였다.
이 문제는 입력값이 작기때문에, 완전탐색을 이용해서 각 좌표마다 값을 옮겨가며,
높이와 너비중 작은 값 만큼 늘려보며 꼭지점이 되는 좌표들이 모두 같은지 확인, 
같다면 넓이구함
의 로직으로 풀었다
이 문제의 포인트는 완전탐색을 꼼꼼하게 잘할 수 있는지?
범위를 넘어가지 않게 잘 설정할 수 있는지? 가 포인트였음
=> [211026 유한욱]

jhy/211026/거북이.py, jhy/211026/숫자 정사각형.py, jhy/211026/싸이버개강총회.py
이번주차 문제들은 상당히 쉬웠지만, 그 안에서도 나의 문제점들이 명확히 드러났다.
문제는 간단해보일수록 더 꼼꼼하게 읽기, try except, set와 같은 기본중이 기본인 것들도 더 잘 공부해놔야겠다.
이 문제는 좌표의 방향과 이동거리에 따라 생성되는 직사각형의 크기를 구하는 문제인데, 그냥 시키는대로 하면 잘 풀리는 문제로 난이도도 낮았던 것 같다.
1. x, y는 0으로 지정해주고, x와 y의 방향을 나타내는 방향 리스트를 만들어줌.
2. F일 경우 x + x_direct, y + y_direct
3. B일 경우 x - x_direct, y - y_direct
4. 2, 3번의 경우 각각 x, y의 최대 최소값을 항상 갱신해줌.
5. R, L인 경우 x_direct 인덱스 변경.
6. (x 최대 - x 최소) * (y 최대 - y 최소)로 직사각형 크기 출력.
7. 테스트 케이스만큼 반복 수행.
이 문제의 포인트는 시뮬레이션을 할 수 있는지와 x, y를 방향에 따라 좌표 이동을 시키는 것이 가능한지가 포인트였던 것 같다.
이 문제는 단순 시간과 닉네임을 비교하면서 개강총회 전과 후 사람들의 채팅 기록이 다 존재하는 사람들 수를 구하는 문제였다. try except와 백준의 채점 방식을 잘 몰라 입력이 더이상 주어지지 않는 경우에 대한 대처가 미흡했지만, 매우 단순한 문제였다고 생각한다. 입력의 범위도 10만이 최대라 전체 탐색을 해도 무방했다.
1. 개강 총회 전 사람을 받기 위한 set before와 후 사람을 받기 위한 set after를 생성.
2. 시간이 개강 총회 전인 사람들에 대해 …
=> [211026] 정하영

jhy/211026/거북이.py, jhy/211026/숫자 정사각형.py, jhy/211026/싸이버개강총회.py, nyc/211026/baekjoon_1051_digit_square.java, nyc/211026/baekjoon_19583_cyber.java, nyc/211026/baekjoon_8911_turtle.java, yhw/211026/거북이.java, yhw/211026/사이버개강총회.java, yhw/211026/숫자정사각형.java
=> [211026] 스터디

jhy/211019/괄호의 값.py, jhy/211019/한 줄로 서기.py
부족한 것이 정말 많이 드러났던 주차였다.
공부를 하고 봐야할 것이 정말 많았던 문제들이었던 것 같다.
이번 주차 문제들은 꼭 제대로 공부해서 다시 풀어봐야 할 것 같다.
이 문제는 주어진 조건에 맞게 스택을 활용하면서 잘 구현해야 하는 문제였던 것 같다. 처음 코드에서 재귀로 풀어볼랬다가 한 단위수준까지만 구해내고 실패를 하는 바람에 재귀로 푸는 걸 포기했고 해설을 봤는데, 스택을 쓰면서 하는 과정의 코드를 이해하지 못해서 추가적인 공부가 필요할 것 같다. 공부해서 다시 풀어보도록 해야겠다.
잘 풀었다고 생각하는 해설을 보면서 다시 시도했지만 역시 아직 부족한 상태. 우선 코드를 따라 쳐보고 공부해봤는데, 아직 손에 익지 않은 것 같다. 다시 풀어봐야 할 듯함.
1. 문자 리스트 끝까지 돌면서 현재 인덱스와 이전 리스트 값을 인자르 받는 재귀함수 선언
2. count = 0(구할 연산 값), flag = True로 초기화(flag는 맞는 문자열인지 판별하는 flag)
3. 현재 인덱스 값이 ) 이거나 ]일 때, 이전 인덱스 값이 (이거나 [이면 count 값에 따라 2 * count(괄호 내부 연산값) or 3 * count와, 다음 인덱스 값 반환 *이 때, count가 0이면 count를 1로 바꿔 계산(count가 0이면 순수 ()이거나 []인 경우라 곱해지는 count가 1이어야 함)
-> 만약 현재 인덱스 값이 3과 같이 주어진 상황에서 다른 경우가 발생하면 flag False로 수정 후 바로 0 출력 및 프로그램 종료
4. 현재 인덱스 값이 (이거나 [일 경우 그 깊이에 따라 괄호 내부 값 …
=> [211019] 정하영

yhw/211102/solve1.java, yhw/211102/solve2.java, yhw/211102/solve3.java
꾸준히 합시다! dfs, bfs는 언제쯤 나오냐??
직사각형들이 주어지고, 직사각형이 지나지 않는 부분의 영역이 몇개나 있는지, 그 영역의 넓이가 각각 어떻게 되는지를
구하는 문제였다!
이 문제는 전형적인 bfs, dfs가 가능한 문제였음
1. 먼제 직사각형의 각 꼭지점들을 입력받아서 반복문을 돌리면서 2차원 배열을 1로 채운다(직사각형)
2. 직사각형이 아닌, 나머지 모눈종이부분의 영역들을 bfs를 돌면서 방문처리를 해주고, 각 영역의 넓이를 priority queue에 담아준다.
3. 개수와 넓이를 오름차순으로 출력해주면 끝
이 문제의 포인트는 2차원배열에대한 탐색이 가능한지를 물어보는 문제였음! bfs, dfs 기초가 튼튼하다면 어렵지 않은 문제였다.
이 문제는 행렬이 주어지고, 왼쪽 -> 오른쪽, 위 -> 아래를 탐색하며 두자리 이상의 문자열들 중 사전순으로 가장 맨 앞에나오는 문자열을 출력하는 문제이다.
그래프 탐색처럼 보이지만, 결이 다른 문제
1. 먼저 막혀있지 않다면 탐색하게끔 해준다
2. 먼저 맨 위에 있을때, 맨 왼쪽에 있을때로 나누어주었다.
2-1. 맨 위나 왼쪽을 골랐을때는 그 전의 값이 막혀있으므로  막혀있는곳이 나올때까지 확인하여, 2자리가 넘는 문자열이면 전역선언한 priority queue에 담아준다.
3. 이제 맨위, 왼쪽이 아닌 중간에 껴있는 값이다.
3-1. 중간에 껴있는값을 탐색할때에는 탐색하는 방향이 아래일때, 위가 막혀있어야하고 오른쪽일때, 왼쪽이 막혀있어야한다.
3-2. 만약 둘다 뚫려있다면, 탐색을 해줄 필요가 없다. 중간에 낑겨있는 값이므로
4. 이렇게해서 가장 …
=> [211102] 유한욱

nyc/211102/baekjoon_1080_행렬.py, nyc/211102/baekjoon_2583_영역구하기.py, nyc/211102/baekjoon_3005_크로스워드.py
`파이썬 코테 감 떨어질까봐 파이썬으로 했습니다. 머리가 아니라 손이 기억하는것 같습니다.`
이 문제는 진짜 BFS/DFS 기본 난이도. 다만 좌표 때문에 좀 헷갈릴 수 있으니, 이에 대해 처리하는 연습할 수 있는 문제
1. 보드 초기화, `visited` 초기화
2. 좌표 4개 받아서 보드에 채움.
3. 보드의 빈 칸만 돌면서 BFS 수행.
1. BFS는 넓이를 구해야 하므로 count를 append할 때마다 세어주게 하고 count를 리턴
4. 전체 BFS 수행 횟수 = 영역 갯수, 넓이 sort 해서 출력
이 문제의 포인트는 좌표 다루기인데, 솔직히 어렵지 않은 난이도이다.
이 문제는 가로로 세로로 문자열을 #일때 파싱해서 문자열 비교를 해주면 되는 문제이다.
1. 가로 -> 세로 2중 포문
1. `#` 만나면 문자열 리셋
2. 최소값과 지금까지 쌓은 문자열 비교하며 **그리디**하게 결과 업데이트
2. 세로 -> 가로 2중 포문, 나머지는 1과 동일
이 문제의 포인트는 단순 구현이다. 구현할 수 있는 방법은 여러가지다. 자신있는 방법으로 실수하지 않기
이 문제는 3x3 영역을 뒤집어가며 A -> B 행렬로 변화시킬 때, 변화시키는 횟수의 최소값을 구하는 문제이다.
움직임, 변화값 등 유형의 최소값을 구할 때 아래 알고리즘이 떠오를 수 있다
- DP + BFS
- 그리디
- 만약 가중치가 다르다면 최단경로 알고리즘
이중 대표적으로 DP + BFS, 그리디 내에서 다 해결이 된다. 이 문제와 같은 경우에는 그리디로 해결할 수 있다.
맨 위 왼쪽부터 한 칸씩 비교하면서 A, B 의 좌표 (x, y) 가 …
=> [211102] 남윤창

jhy/211026/거북이.py, jhy/211026/숫자 정사각형.py, jhy/211026/싸이버개강총회.py, nyc/211026/baekjoon_1051_digit_square.java, nyc/211026/baekjoon_19583_cyber.java, nyc/211026/baekjoon_8911_turtle.java, yhw/211026/거북이.java, yhw/211026/사이버개강총회.java, yhw/211026/숫자정사각형.java, yhw/211109/problem1.java, yhw/211109/problem2.java, yhw/211109/problem3.java
꾸준히 문제를 풉시다. 최단경로를 구하는 문제를 헷갈리다니..
8이 포함된 개수가 가장 적은 수에서 8의 총개수를 구하는 그리디한 문제였다.
무작정 숫자를 보지않고 완전탐색을 돌렸을경우? 시간초과가 당연하게 나게 된다.
그러므로 그리디 하게 생각해보자.
먼저 숫자의 자리수가 다르게 된다면? 모든 자리수에 8이 안들어가게 할 수 있기 때문에 0을 출력해준다.
이제 나머지 같은 자리수의 경우가 문제이다.
1. 큰 자리수부터 확인한다
2. 양쪽의 자리수가 같으면서, 8이 나왔다? 그 자리에는 무조건 8밖에 들어갈 수 없다.(큰 자리수부터 비교하기 때문)
3. 양쪽의 자리수가 다르다? 반복문 break(큰 자리수부터 비교하기 때문에, 그 아래 자리수에있는수들은 모두 8이 아닌 경우가 존재)
이 문제의 포인트는 수학적 사고를 요하는 문제였다. 코딩테스트 문제로는 나올 가능성이 희박하다고 생각... 아마?
이 문제는 모든 노드에서 갈 수 있는 곳으로 최대한 많은 파밍을 하면 되는 문제
시작점이 모든 노드가 될 수 있기때문에 플로이드 와샬을 떠올리게 되었다.
(입력값도 100으로 가능하다!)
1. 먼저 모든 map을 무한대로 초기화 한뒤, 자기 자신으로 가는 노드의 경우 0을 입력
2. from -> to, to -> from 인접 행렬을 이용해서 연결 시켜준다.
3. 플로이드 와샬기법을 이용해서 a -> b노드로 가는 모든 시작, 끝 경로를 조정하여 준다
4. a -> b로 가는 최단 경로의 거리를 가지고, limit 범위를 넘지 않는 모든 경로를 각 시작 노드 별로 구해서 가장 큰 경우가 파밍을 제일 많이 할 수 …
=> [211109] 유한욱

jhy/211102/영역 구하기(bfs).py, jhy/211102/영역 구하기(dfs).py, jhy/211102/크로스워드 퍼즐 쳐다보기.py, jhy/211102/행렬.py
`한 줄 소감을 쓰시오`
이 문제는 dfs, bfs의 완전 기본이지만 그래프를 한 번 정리해주는 과정이 필요한 문제였다. 처음 dfs, bfs를 보는 수준에서 풀어본 상태라 상당히 힘들었고, 배운 개념이 바로 적용되지 않아 솔루션을 봤다. 이해는 확실히 된 것 같고 이제 문제풀이를 통해 정복하면 될 것 같다.
<공통>
1. m, n, k를 입력 받으며 m, n 만큼의 그래프를 0으로 초기화
2. k는 x1, x2, y1, y2 좌표로 받음으로써 해당 직사각형이 차지하는 영역만큼을 그래프에서 1로 변환
3. 그래프를 돌면서 dfs/bfs 함수 실행하여 반환되는 직사각형 넓이 저장
4. 직사각형들 넓이와 개수 출력
<dfs함수>
1. 자기 자신은 1로 변환
2. 상하좌우 네 방위로 움직이기 위한 좌표계 만들고, 탐색 조건이 맞다면 다음 좌표를 기준으로 다시 dfs 재귀적 호출
3. count(직사각형 넓이) 출력
<bfs함수>
1. queue에 x, y 좌표 넣고, count = 1
2. queue가 완전히 빌때까지, 즉 탐색 범위에 계속 해당하는 한 사방으로 진행하며 count += 1
3. 방문되지 않은 좌표 다시 추가하고, 범위에 해당할 시 반복
이 문제의 포인트는 다른 무엇보다도 dfs, bfs을 잘 쓸 수 있는가에 대한 문제였다고 생각한다. 아직 경험이 부족해 바로 혼자 짤 수 있는 상태는 아니지만 그렇게 될 수 있도록 하겠다.
이 문제는 주어진 조건에 맞게 행렬의 특성을 활용하여 문제를 해결할 수 있는가에 대한 문제였다고 생각한다. 행렬을 잘 못 건들던 나였는데 일단 코드가 돌아가게 구현하는 데에는 …
=> [211102] 정하영

jhy/211109/서강그라운드.py, jhy/211109/예산.py, jhy/211109/팔.py
`새로운 개념이나 잘 쓰지 않던 개념을 많이 발견한 주차 문제였다고 생각한다.`
이 문제는 모든 경우를 탐색하면 안되는 문제였다. 주어진 입력의 범위가 20억이라 브루트 포스를 할 경우 시간 초과가 날 수 있다. 따라서 8의 최소 개수를 효율적으로 찾기 위해 그리디 알고리즘을 적용하였다.
1. L, R을 문자열로 받아 그 길이가 다르면 무조건 0
2. L, R이 같으면 무조건 한쪽의 '8' 문자의 개수
3. 서로 다른 값이면서 같은 자릿수인 경우, 0번지부터 시작해 같은 값이면 계속 진행
4. 같은 값일 때 그 값이 8인 경우 count해주며, 다른 값이 나오는 순간 count 출력
이 문제의 포인트는 입력값을 통해 그리디를 선택해 풀 수 있는지에 대한 부분이 포인트였던 것 같다. 문제를 풀면서 예외없이 모든 경우에 대해 잘 돌아가게 해야하는데 예외를 찾느라 애를 먹었다.
이 문제는 최단 경로를 잘 몰라 bfs로 풀어보려고 했다가 실패한 문제이다. 인접한 지역끼리의 거리가 각각 다르기 때문에 bfs로 해결할 수 없는 알고리즘으로, 최단 경로 중 다익스트라나 플로이드 워셜 알고리즘을 통해 접근해야 한다. 알고리즘 숙지가 안되어 있어 풀 수 없었던 문제라 솔루션을 봤다.
<다익스트라>
1. 시작 지역으로 가기 위한 최단 경로는 0으로 haepq에 삽입 (거리, 시작점)
2. q가 비어있지 않는 한 가장 최단 거리 정보가 짧은 경로 정보 꺼내기
3. 처리되지 않은 지역이 있으면 인접한 지역 중 거리가 더 짧은 지역으로 경로 설정 
<메인>
1. 지역별로 인접 지역과 그 길이를 담는 2차원 리스트 생성
2. …
=> [211109] 정하영

yhw/211116/가르침.java, yhw/211116/계란으로 계란치기.java, yhw/211116/야구공.java, yhw/211116/연세 토토.java, yhw/211116/최고의 피자.java, yhw/211116/행복 유치원.java
꼼꼼하게 문제를 풉시다
이 문제는 k개의 단어를 가르쳐서 학생들이 읽을 수 있는 최대한의 조합을 뽑는 문제였다.
1. 이 문제는 antic은 무조건 포함되어야 하기때문에 5개보다 가르칠 수 있는 단어가 적게되면 아무것도 가르칠 수 없으므로, 
예외처리를 해준다.
hash - 모든 단어의 겹치지 않는 알파벳 set
hashCheck - 모든 단어의 각각, 단어별 겹치지 않는 알파벳 set배열
2. hash에 있는 단어만큼, 더 많이 가르칠 수 있다면 모든 단어를 가르칠 수 있기때문에 n의값 자체가 결과가 됨
3. 작을 경우에는 조합을 이용해서 최대값이 나오는 알파벳의 조합을 구해서 모두 탐색
이 문제의 포인트는 조합을 얼마나 꼼꼼하게 풀 수 있는지가 포인트
이 문제는 원생들을 적어도 한명 이상의 조로 나누어 큰놈, 작은놈의 차이의 합을 최소로만드는 문제였음
1. 이 문제는 그리디하게 각 조에 키의 크기가 제각각인 놈들이 들어오게 된다면, 정렬을 통해서 최대 최소를 구해 줄 수있다.
2. 각 조의 최소 조합을 구하기위해서는 k개의 조를 이룰 수 있기때문에 k개의 조로 n명의 학생을 나눠야 하기때문에 각각의 차이는 n-k개가 나오게된다
3. 모든 1대 1 차이를 구해서 n-k개를 합해주면 끝
이 문제는 그리디하게 생각하는게 포인트였음
이 문제는 많은 수의 강의를 수강해야 하므로 정렬을 이용해야겠다고 생각했음
1. 이 문제는 수강인원이 모자란 강의면 0보다 커야하므로 1을 넣어주고, 나머지는 젤 적게 마일리지를 올린 학생이랑 같은 마일리지를 등록시킨다.
2. 작은 등록 마일리지부터 합해가며, 성준이가 가진 최대 …
=> [211116]유한욱

yhg/Thebestpizza.py, yhg/Yonsei TOTO.py, yhg/baseball.py, yhg/edu.py, yhg/egg.py, yhg/kidsgarden.py, yhg/pal.py, yhg/seogang.py, yhg/yiesan.py
모든 문제를 푼 후에 작성하겠습니다. 
이 문제는 배울 수 있는 알파벳의 조합이 있고 그 조합의 알파벳을 개수에 맞춰 선정하여 배웠을 때 읽을 수 있는 단어개수의 최대값을 출력하는 문제입니다. 
모든 알파벳을 확인해봐야 하고 이를 일일히 확인하는 것은 26개중 k 개를 고르는 것 이므로 여차하면 시간초과가 날 수 있기 때문에 조합을 하나씩 확인할 때 이미 확인했던 알파벳은 제외하고 확인해봐야한다. 
1. 남극언어에 필수로 포함되는 단어인 a,n,t,i,c를 미리 알고있어야 한다고 가정하고 set에 추가한다.
2. 입력받은 단어의 처음과 끝 4자리는 필수적으로 포함되므로 미리 제거하고 제거한 단어를 list에 담는다.
3. 주어진 k보다 가르칠 알파벳 개수가 크다면 가르칠 알파벳보다 알아야할 알파벳이 많으므로 return 한다.
4. 만약 k보다 가르칠 알파벳 개수가 작다면 아직 더 가르칠 알파벳이 존재하므로 아래의 규칙을 따른다
 4-1  만약 visited(이미 조합에 넣어본 알파벳)에 a+(0~25)가 없다면 해당 조합을 넣어보고 다시 제거한다. 
4-2 만약 넘겨받은 알파벳의 개수가 k와 같다면 입력받은 단어를 확인한다. 
4-3 만약 입력받은 단어에 가르친 알파벳 이외에 것 이나오면 넘어가고 가르친 알파벳이 모두 있으면 단어의 개수를 1 늘려준다.
4-4 카운트한 단어의 개수를 현재 최대값과 비교하여 최대값을 업데이트한다.
5. 결과를 출력한다.
이전에 이미 한번 체크한 것들은 다시 검사하지 않는 로직을 추가하는게 분명히 중요하다고 했었는데 이를 또다시 망각했다. 다음에는 이런 실수를 절대로 하지 …
=> [211116] 유현근

jhy/211116/Yonsei TOTO.py, jhy/211116/가르침.py, jhy/211116/계란으로 계란치기.py, jhy/211116/야구공.py, jhy/211116/최고의 피자.py, jhy/211116/행복 유치원.py
`접근할 아이디어가 잘 떠오르지 않았던 문제가 간혹 있었다. 더 많은 유형을 많이 익숙하게 해둬야 할 듯..`
이 문제는 자료구조와 조합을 잘 활용하고, 그리디한 부분을 파악해 잘 처리할 수 있는지에 대해 물어보는 문제였던 것으로 파악된다. 채점 중 80% 부분에서 계속 실패가 뜨는데 잘 해결되지 않아 결국 본인의 풀이 방식과 좀 다르게 푼 솔루션을 보긴 했지만, 코드는 아직 해결되지 않은 본인 코드로 올렸음. 
솔루션을 봤을 때는 비트 마스킹을 활용한다고 되어있는데 아직 비트 마스킹에 대해 이해가 완벽히 된 상황이 아니라 본인의 풀이를 해결하고 비트 마스킹 부분도 추가적으로 공부할 계획.
...
결국 해결을 보지 못하고 솔루션대로 코드 활용했다.
비트 마스킹은 a,b,c 중 a,c가 존재할 경우 101로 표현하는 식으로 각 내부 자료를 이진수로 표현하는 방식이다. 이 방식을 활용하면 더 빠른 시간, 더 간결한 코드, 더 적은 메모리 사용을 할 수 있어 시간 초과나 메모리 초과가 나지 않는 방법으로 쓰인다. 알파벳이 총 26개라서 모든 알파벳을 쓴다고 해도 파이썬의 32비트보다는 작기 때문에 비트 마스크를 활용하는 방법이 매우 효율적인 방법이 된다.
1. 어떤 단어도 기본으로 다 가지고 있는 a, n, t, i, c를 예약된  list에 담아둠.
2. 단어를 각각 set으로 입력받아 기본값을 빼서 어떤 글자를 가지고 있는지 보기 쉽게 해둠.
3. words에 존재하는 알파벳의 bit을 담아둠
4. words들에 대해 solution(k - 5) 출력
<solution 함수>
1.  k < 0인 경우 어떤 …
=> [211116] 정하영

jhy/211130/드래곤 커브.py, jhy/211130/생태학.py, jhy/211130/어린 왕자.py, jhy/211130/주사위 굴리기.py
`시뮬레이션에 상당히 약한 모습을 보였던 주차.`
이 문제는 주사위 전개도를 펼쳐 생각하면 생각보다 수월하게 해결할 수 있는 문제였다고 생각한다. 본인은 문제를 읽었을때부터 막막하고 전개도를 펼쳐 방향에 따른 전개도를 떠올릴 생각을 못해 결국 솔루션을 봤다.
1. 동서남북을 가리키는 dx, dy 선언
2. 주사위를 방향에 따른 숫자 정보를 나타내는 direction 선언(위: 0, 동: 1, 서: 2, 북: 3, 남: 4, 바닥: 5)
3.  명령에 따라, direction의 각 값을 0~4로 나타냈기 때문에 각 명령의 -1로 명령 수행
4. x, y값을 이동 방향에 따라 이동
5. x, y가 지도를 벗어날 경우 원래대로 돌려놓음
6. 이동 방향에 따라 주사위 전개도 위치 수정
7. 지도 칸이 0이면 주사위 바닥 값 복사
8. 각 명령에 대해 주사위 윗면 출력
이 문제의 포인트는 주사위 전개를 헷갈리지 않고 시뮬레이션을 잘 수행할 수 있는지가 중요한 포인트였다고 생각한다.
이 문제는 규칙을 찾아 시뮬레이션을 해결할 수 있는지를 확인할 수 있는 문제였던 것 같다. 규칙을 찾을 생각 자체를 못해 접근을 못했고, 결국 솔루션을 참고했다.
`이 문제의 규칙: 이전 세대의 정보를 뒤집어 1을 더해주면 현재 세대를 구할 수 있음.`
1. x, y의 방향 정보를 나타내는 dx, dy 생성
2. move 리스트에 이동 방향 저장
3. move에 저장한 이동방향 불러와서 다음 세대 드래곤 커브 형성
4. 드래곤 커브에 해당하는 좌표 arr에 추가
5. 각 꼭짓점이 드래곤 커브의 일부인 정사각형 개수 출력
이 문제의 포인트는 …
=> [211130] 정하영

nyc/211130/baekjoon_1004_어린왕자.py, nyc/211130/baekjoon_14499_주사위굴리기.py, nyc/211130/baekjoon_15685_드래곤커브.py, nyc/211130/baekjoon_4358_생태학.py
`수학 오랜만에 풀어서 재밌었다.`
이 문제는 시키는대로 주사위 굴리면 되는 문제이다.
저번주차 숙제에서 야구공 게임에서 힌트를 얻어서 주사위 6면을 각각 따로 변수로 하드코딩 해서 간단하게 풀었다.
코테 시뮬레이션 유형에서 유용하게 쓸 수 있는 스킬을 얻은것 같다.
1. 4가지 굴리는 함수를 만든다.
- 문제에서 주어진 주사위 단면은 그대로 유지하고, 해당 면에 쓰여진 값만 이동시키도록 구현했다.
- ex): 위쪽으로 굴리는 경우 3, 4(d3, d4)번째 면은 그대로 있고 나머지 면을 하나씩 밀어준다. `d2, d1, d5, d6 -> d6, d2, d1, d5`
2. 커맨드를 하나씩 실행시킨다.
3. 다음 위치가 좌표를 벗어났다면 무시
4. 커맨드에 알맞은 방향에 따라 이동하도록 구현한다.
5. 이동한 후, 해당 위치의 값이 0이라면 `d1`위치의 값을 보드에 복사, 
6. 0이 아니라면 `d1`위치에 보드의 값을 복사 하고 보드는 0으로 초기화
이 문제의 포인트는 시뮬레이션을 최대한 간결하게 풀기
이 문제도 시키는 대로 하면 되는 시뮬레이션 유형이다.
어려운 점은 드래곤 커브의 움직임이 되게 복잡한데, 이걸 어떻게 간단하게 구현할 것인가이다.
- 90도 시계방향으로 돌리고
- 끝점에 붙이기
나는 위 규칙을 어떻게 구현할지 잘 모르겠어서 직접 몇 번 그려봤다.
저걸 코드로 어떻게 옮길까 고민을 했고, 방향을 키워드로 잡고 고민하다가 아래의 해결법을 생각했다.
시작점부터 움직이는 방향을 미리 저장하고 움직이도록 구현했다.
(0세대, 오른쪽 방향)으로 시작할 경우 3세대 는 어떻게 움직여야 하는지 …
=> [211130] 남윤창

yhw/211130/1.java, yhw/211130/2.java, yhw/211130/3.java, yhw/211130/4.java
감을 잃지 않도록 꾸준히 풀자
이 문제는 주사위를 어떻게 굴려야할지 모르겠어서 직접 집에있는 육면체의 지우개를 가지고 계산을 해보며 하드코딩하여 이동할때에 위치와 비교하며 구현해주었다.
1. 이 문제는 구현유형의 문제로, 크게 
2. 주사위 굴리기, 맵에 있는 숫자와 주사위에 붙어있는 숫자를 비교하며 숫자를 변경하기
3. 윗면 출력하기
세가지 부분으로 나눌 수 있었다.
- 굴리기의 로직은 상, 하, 좌, 우에 맞게 네가지 경우에대해서 모두 코딩해주면 됨
- 주사위의 윗면과 밑면을 명확히 구분하여 출력
이 문제의 포인트는 주사위를 어떻게 굴려야하는지가 가장 큰 포인트였다. 주사위 굴리는 방법에대한 방향을 찾고나서는 크게 어렵지 않았음
이 문제는 정말 까다로운 구현문제로 리스트를 이용하여 풀었다.
최대 100 X 100의 맵을 탐색해야 하므로 시간 복잡도를 낮추기위해, 드래곤 커브가 지나가는 루트에 대해서 LIST에 담아주도록 한다.
이때 리스트에 담아주는 방향 로직의 규칙성을 발견해보면,
0 -> 0 1 -> 0 1 2 1 -> 0 1 2 1 2 3 2 1
왼쪽과 오른쪽을 기준으로 대칭(오른쪽은 + 1) 이라는 규칙이 나오게 된다.
이를 바탕으로 dir.add((dir.get(j) + 1) % 4); 을 하여 LIST를 구성해준다.
이때 %4를 하는 이유는 뱡향이 총 1,2,3,4로 네개의 경우이기 때문!
이렇게 방향을 구했다면, 맨 처음 공을 던지기 시작한 위치부터 MAP에 체크를 해주면 된다.
출력은 100 X 100의 2차원 배열에서 네 꼭지점이 체크된 1X1 영역의 수를 출력한다
이 문제의 포인트는 …
=> [211130] 유한욱

jhy/211207/미세먼지 안녕!.py, jhy/211207/암호 만들기.py, jhy/211207/지뢰 찾기.py, jhy/211207/추월.py, jhy/211207/친구 네트워크.py
`한 줄 소감을 쓰시오`
이 문제는 개인적으로 많이 취약한, 꼼꼼함을 매우 필요로 하는 구현 및 시뮬레이션 문제였다. 시간복잡도를 통해 3중 포문까지도 쓸 수 있겠다는 생각까지는 잘 해낸 것 같지만, 디버깅하는데 정말 많은 시간을 들였다. 해결해냈다는 것에 매우 뿌듯하지만, 훨씬 빠르게 풀고 싶다.
1. 주어진 시간만큼 다음을 반복.
1-1. 미세먼지 확산
1-2. 공기청정기의 바람 동선따라 먼지 이동
<미세먼지 확산>
1. 구사과의 방 크기만큼의 빈 방 생성
2. 매 칸마다 진행하면서 다음을 반복
2-1. -1일 경우 다음 반복문 수행
2-2. -1 아닌 경우, 좌우상하 4방향과 True 값을 각각 key, value로 하는 dict 생성
2-3. Arc는 A(r,c) 좌표에 들어갈 값, around는 인접한 칸에 들어갈 값
2-4. 방을 넘어서지 않으면서 -1이 아닌 경우에 대해 4 방향에 대해 확산이 가능하면 유지, 아니면 False값으로 변환 및 Arc값 조정
2-5. dict에 있는 방향별 value값을 확인하며 around 값 넣어주기
2-6. 구사과의 방의 값을 빈 방의 정보대로 채우기
<공기 청정기 동작>
1. 청정기의 위, 아래 순회 함수를 따로 생성(진행하는 방향만 다르게 해주면 됨.)
2. 청정기의 진행동선 정보를 담기 위한 deque 생성
3. 동선에 따라 정보 담기
4. 청정기 오른쪽 값은 0
5. 청정기 오른쪽 2번째 값부터, deque에서 popleft해가며 넣어주기
이 문제의 포인트는 시뮬레이션을 꼼꼼하게 확인하면서 구현해나가는 것이 매우 중요했다. 나에게 아직 매우 부족한 …
=> [211207] 정하영

nyc/211207/baekjoon_17144_미세먼지안녕.py, nyc/211207/baekjoon_1759_암호만들기.py, nyc/211207/baekjoon_2002_추월.py, nyc/211207/baekjoon_2140_지뢰찾기.py, nyc/211207/baekjoon_4159_친구네트워크.py
`늦었습니다 제성합니다`
이 문제는 미세먼지가 확산 되는 과정과 공기청정기가 동작하는 과정을 정확히 이해하고 구현하면 되는 문제이다. 미세먼지가 확산이 모든 칸에서 동시에 일어나기 때문에 이를 구현하는게 꽤 까다로운 문제이다.
동시에 확산되는 것을 해결하기 위해서는 2개의 2차원 배열을 선언해서 deepcopy를 활용해서 풀면 해결할 수 있다.
1. 에어컨 위치 구하기 (행 좌표만 구하면 됨)
2. 같은 크기의 2차원 임시 배열 선언하고 에어컨 위치 그대로 옮기기
3. 2차원 배열 순차 탐색 하며 확산 시킨 값을 임시 배열에 저장하기
- 확산은 문제에서 주어진 대로 하기.
- 다만 0을 나누려고 하는 오류가 발생할 수 있기 때문에 0이하라면 진행하지 않고 리턴
4. 임시 배열 -> 기존 배열로 딥카피
5. 공기청정기 상단, 하단 청소 진행
- 공기청정기부터 벽 타고 가면서 값을 queue에 넣기
- queue에 넣은 값들을 공기청정기 다다음 칸부터 다시 그대로 붙여넣기
이 문제의 포인트는 함수 분리와 2차원 배열 딥카피 사용
이 문제는 전형적인 백트래킹 문제이다. 
C개의 문자가 주어졌을때 길이가 L인 오름차순 암호를 모두 출력하면 된다.
1. 우선 주어진 알파벳들 오름차순으로 정렬
2. 뎁스가 L일 때까지 백트래킹 재귀 수행
- 오름차순으로 정렬된 알파벳 하나씩 사용해보며 재귀 들어가기.
- 다만 모음과 자음을 미리 카운트 하기 위해 v_cnt, c_cnt라는 값들을 사용했음.
3. 뎁스가 L이라면 한 개의 모음, 두 개의 자음으로 이루어졌는지 검사하고 아니라면 리턴, 맞다면 문자열 출력하고 리턴
이 …
=> [211207] 남윤창

yhw/211207/미세먼지안녕.java, yhw/211207/암호 만들기.java, yhw/211207/지뢰찾기.java, yhw/211207/추월.java, yhw/211207/친구네트워크.java
코딩테스트의 기초는 구현! 구현!을 통해서 기본 구현력 및 피지컬을 키우자!!!
이 문제는 공기청정기의 확산을 이용하여 남아있는 미세먼지의 총량을 구하는 문제였음
1. 시간초를 관리할 반복문 생성
2. 공기청정기의 윗부분, 아랫부분을 나눔
3. 각각 반 시계방향, 시계방향으로 미세먼지의 확산하는 로직을 구현
4. 시간초가 완료되면 남아있는 미세먼지의 총량을 구한다
이 문제의 포인트는 시계방향, 반시계방향의 확산 로직을 구하는게 가장 큰 문제였다... 이부분에서 명확하게 구현하지 못해서 4초가 넘어가는 미세먼지부터는 답이 틀림 ㅠ
이 문제는 모음 1개이상, 자음 2개 이상의 알파벳으로 암호를 구현해 사전순으로 나열하는 문제
1. 모음과 자음 구분하여 list에 담아준다
2. 모음의 갯수를 1개이상, 자음의 갯수를 2개이상으로하여 조합을이용해 뽑아줌
3. 나온 문자열을 collection의 sort를 이용하여 정렬하여 출력
이 문제의 포인트는 재귀를 이용하여 문자열 조합을 뽑아내는게 포인트
전형적인 재귀 조합 문제였다.
이 문제는 알수없는 영역에 지뢰의 최대갯수를 구하는 문제였다.
1. 이 문제는 먼저 알수없는 미지의 영역에대해 2차원 반복 탐색을 진행한다.
2. 최대 지뢰의 수를 구해야하기때문에 미지의 영역을 우선 모두 지뢰가 있다고 판단(answer++)
3-1. 탐색을 진행하면서 8방향에 0이 있다면 지뢰가 있을 수 없으므로 answer -1을 진행
3-2. 0이 없다는걸 확인했으면, 다시 1 ~ 9 사이의 숫자가 8방향에 존재한다면 -1한 값을 8방향에 넣어준다.
4. answer(지뢰의 최대개수)를 …
=> [211207] 유한욱

yhw/211215/농장관리.java, yhw/211215/치즈.java, yhw/211215/토달기.java
`한 줄 소감을 쓰시오`
이 문제는...
- 몇 분?
1. 이 문제는...
이 문제의 포인트는...
이 문제는...
- 몇 분?
1. 이 문제는...
이 문제의 포인트는...
이 문제는...
- 몇 분?
1. 이 문제는...
이 문제의 포인트는...
=> [211215] 유한욱

yhg/ice.py, yhg/popul.py
`한 줄 소감을 쓰시오`
이 문제는...
- 몇 분?
1. 이 문제는...
이 문제의 포인트는...
이 문제는...
- 몇 분?
1. 이 문제는...
이 문제의 포인트는...
이 문제는...
- 몇 분?
1. 이 문제는...
이 문제의 포인트는...
=> [211228] 유현근

jhy/211223/컨베이어 벨트 위의 로봇.py, jhy/211223/후보 추천하기.py
`한 줄 소감을 쓰시오`
이 문제는...
1. 이 문제는...
이 문제의 포인트는...
이 문제는 주어진 진행 과정에 따라 시뮬레이션을 잘 구현하기만 하면 된다. 발생할 수 있는 예외 처리만 잘 생각해주면 문제 없이 답을 잘 도출해낼 수 있다고 생각한다.
1. 추천받는 번호  number를 deque로 생성
2. 후보를 등록할 딕셔너리 candidates 생성
3. 사진틀이 다 채워진 경우 이미 있는 후보자가 추천된다면 카운트, 아니면 기존 후보자 중 추천 수 제일 작고 candidates.values() 리스트의 가장 오래된 후보자 삭제 후, 새 후보자 등록 후 카운트 1
4. 후보자 번호만 들어있는 리스트 반환
5. 추천수만큼 3, 4 반복 후 나오는 결과 리스트 정렬
6. 리스트의 길이만큼 후보자 수 출력
이 문제의 포인트는 시뮬레이션을 잘 구현해낼 수 있는지와 더불어, 발생할 수 있는 예외 케이스를 잘 처리할 수 있는지가 포인트였다고 생각한다. 제출시 100프로가 나와도 틀렸습니다가 뜨길래 처음에 당황했지만, 결과 리스트가 항상 다 채워지지 않을 수도 있다는 경우를 떠올려 맞힌 문제였다.
이 문제는 단순 구현과 시뮬레이션이지만 시뮬레이션이 잘 돌아가는지 테스트 케이스 확인하는 게 너무 힘들었다. 테스트 케이스가 커짐에 따라 틀리는데 아직 어디서 틀렸는지 확실히 찾지 못해 시도하는 중.
1. 전체 단계 수와 무한루프 종결을 위한 플래그 생성
2. 로봇과 컨베이어 벨트 오른쪽으로 한칸씩 이동
3. 로봇이 다음칸이 비어있고, 내구성이 있는 칸으로 한칸씩 이동
4. 로봇은 n번째 칸부터 2n번째 칸까지 …
=> [211223] 정하영(진행중..)

yhw/211223/보물섬.java, yhw/211223/컨베이어벨트 위 로봇.java, yhw/211223/후보추천하기.java
구현을 통해서 피지컬을 기르자
전형적인 그래프 탐색문제였다. 크게 어렵지 않았음
육지인 경우에 BFS탐색을 진행하였다.
1. 좌표와 탐색한 길의 count를 탐색한다
2. 제일 긴 탐색결과 = 첫 좌표로부터 현재 좌표까지의 최단거리
3. 이 결과를 바탕으로 육지의 모든 좌표에대해 탐색을 진행하여 가장 긴지점을 찾아서 결과를 반영
이 문제의 포인트는 bfs를 이용하여 탐색할 거리의 최단거리를 구하는게 포인트였다
이문제는 사진틀의 길이가 주어져있고, 이러한 사진틀이 꽉차게되면 가장 빈도가 적고 빈도가 모두 일치하다면 가장 들어온지 오래된 사진이 제거된다.
해시를 이용하였고 순서, 빈도에 대한 해시를 생성함
1. 이미 사진틀(빈도)에 있는 경우 빈도수를 +1 해준다
2. 사진틀에 없는경우 사진틀이 꽉차있는지 확인
2-1. 사진틀이 꽉 차있지 않다면 빈도는 1로 설정하여 사진틀에 추가
2-2. 사진틀이 꽉 차있다면, 빈도가 적고, 순서가 앞인 녀석을 찾아서 제거한다
3. 이 모든 과정을 거친 후 순서대로 출력
이 문제의 포인트는 해시를 이용해서 시간복잡도를 줄이는게 포인트였던거 같음
이 문제는 구현문제로 문제설명이 조금 복잡하였다.
로직은
회전 -> 
회전에 따른 로봇위치 수정 -> 
로봇이 내리는 위치에 도달하지 않으면 인덱스를 +1 ->
0번(올리는 위치) 내구도가 현재 0이 아니라면 로봇을 올림 ->
컨베이어 벨트를 모두 조사하여 내구도가 0 인 벨트가 k개라면 종료
이 문제의 포인트는 컨베이어 벨트와 로봇의 이동을 꼼꼼하게 구현하는것이 포인트였다
=> [211223] 유한욱

nyc/211223/baekjoon_1713_후보추천하기.py, nyc/211223/baekjoon_20055_컨베이어벨트위로봇.py, nyc/211223/baekjoon_2589_보물섬.py
`시뮬레이션은 정말 텐션이 중요해보인다. 오래 쉬니까 너무 오래걸린다. 시뮬레이션은 꼭 꾸준히 하자. 그리고 최대한 쉽게 풀 수 있는 방법들을 머리속에 기억해두자.`
이 문제는 L로 이루어진 곳들의 최대 거리를 구하면 된다.
따라서 BFS나 DFS를 사용하여 L들을 완전탐색하면 된다.
- 15분
1. 2차원 배열 전체 탐색하며 각 좌표에서 BFS 수행 (L일 때만)
2. BFS를 수행하는데, W이거나 좌표범위를 벗어나면 -> continue
3. 이미 방문했다면 -> continue
4. L이라면 거리 +1 해서 다시 queue에 삽입
5. 최대 값 출력
이 문제의 포인트는 BFS 빠르게 풀기.
이 문제는 쉬워보이는데 은근 까다로운 문제이다.
개수를 오름차순으로 계속 정렬해야 하는 점에 있어서 우선순위 큐를 쓸까 생각했었다. 그러나 중간레벨의 값의 개수를 더해야 하는 과정이 포함되기 떄문에 heapq의 사용은 포기했다.
그래서 빠르게 그냥 시뮬레이션 유형임을 파악해야했고, 인풋의 크기가 작은 것을 이용해서 그냥 deepcopy와 sort를 거리낌없이 사용했다.
- 47분
0. 후보들의 번호와 개수, 틀에 게시된 시간을 저장하기 위한 Nx3차원 배열을 선언한다. 그리고 사진 틀은 set을 이용하여 구현
1. 만약 후보가 이미 사진 틀에 있다면 카운트 += 1
2. 후보가 사진 틀에 없다면 가장 득표수가 낮은 후보 제거 -> sort(key=lambda) 를 이용해서 쉽게 해결
3. 사진 틀에 남아 있는 후보들을 오름차순으로 정렬하여 출력
이 문제의 포인트는 자료구조를 얼마나 깔끔하게 정리하여 문제를 풀 수 …
=> [211223] 남윤창

nyc/211228/baekjoon_16234_인구이동.py, nyc/211228/baekjoon_2573_빙산.py
`한 줄 소감을 쓰시오`
이 문제는 거의 시뮬레이션이라고 봐도 되고, 부분상 BFS나 DFS를 이용해서 빙산이 두 덩어리로 분리 되었는지만 파악하면 되는 유형의 문제이다.
- 30분
1. 빙산이 두 덩어리로 분리 되었는지 파악
- BFS 사용해서 0이 아닌 곳들의 이어져 있는 정도 파악 
- 여기서 만약 모든 칸이 0이라면 0 출력하고 프로그램 종료
2. 한 덩어리라면 빙산을 전체적으로 녹임.
- 빙산을 녹이는 방법은 deepcopy 를 사용하거나, 바꿀 좌표를 미리 리스트로 지정해놓는 방법이 있다. 나는 후자 사용
이 문제의 포인트는 구현 능력 및 자료구조 적절히 사용
이 문제는...
- 몇 분?
1. 이 문제는...
이 문제의 포인트는...
이 문제는 두 나라 인구수 차이에 따라 인구 이동을 시키는 문제이다. 
그리고 인구 이동이 더이상 일어나지 않을 때까지 반복하는데 최대 2000 회이다.
- 옛날에 풀어서 모름.
1. 최대 2000번 반복
2. BFS 2차원 배열 순회하며 not visited인 경우에 해당 좌표부터 수행
3. 연합할 수 있는 도시라면 visited처리
4. 연합 가능한 모든 도시의 인구 이동 처리 하고 인구 이동이 발생했다면 2로 이동
5. 인구 이동이 발생하지 않았다면 반복을 멈추고 정답 출력
이 문제의 포인트는 인구 이동 좌표 처리하기..?
=> [211228] 남윤창 (진행중...)

yhg/Palin.py, yhg/mirror.py, yhg/startTaxi.py
`한 줄 소감을 쓰시오`
이 문제는 주어진 조건과 시간안에 최단경로로 손님과 도착지를 판단하여 이동할 수 있는지, 이동할 수 있다면 마지막에 남은 연료를 그렇지 않다면 -1을 출력하는 문제입니다. 
- 2시간 
1. 출발지와 도착지에 대한 좌표를 미리 리스트에 저장한다. 
2. 택시의 시작 좌표를 기준으로 제일 가까이 있는 손님을 찾는다.  
- [손님을 찾으러 가는 과정]
1. bfs를 탐색하면서 제일 먼저 만나는 손님의 길이를 따로 저장한다. 
2. 저장한 거리의 있는 손님보다 거리가 먼 곳은 탐색하지 않는다. 
3. 만약 탐색하는 과정에서 똑같은 거리의 손님이 여러명이라면 heappush를 하여 정렬 순서는 거리,행 , 열 순으로 정렬하여 리스트에 저장한다. 
4. 손님을 찾지 못했다면 -1을 리턴하고 그렇지 않다면 제일 먼저 태워야 하는 손님을 리턴한다. 
3. 손님을 찾지 못했다면 그 즉시 -1을 출력하고 종료한다. 손님을 찾았다면 현재 기름으로 갈 수 있는 거리인지 확인한다. 
4. 현재 기름으로 갈 수 있는 거리라면 기름을 소모하고 해당 손님의 도착지의 정보를 찾기 위해서 미리 저장해두었던 도착위치의 인덱스를 찾아 도착지까지 이동을 시키는 함수에 전달한다. 
5. 도착지가 이동을 하면서 도착지의 좌표와 비교해가면서 bfs로 이동한다. 
6. 도착지에 도착하면 이동한 거리와 좌표를 리턴한다.
7. 이동한 거리가 현재 기름으로 갈 수 없는 거리이거나 도착지가 제대로 존재하지 않아 도착지에 제대로 도착하지 못하면 -1을 출력하고 종료한다. 
8. 만약 제대로 이동했다면 이동한 거리만큼 기름을 충전하고 …
=> [220118] 유현근

jhy/220118/거울 설치.py, jhy/220118/스타트 택시.py, jhy/220118/팰린드롬 만들기.py
`코드가 길어 그런지 많이 힘들고 어려워했던 문제들`
이 문제는 시간 초과를 피해 BFS를 활용해 풀면 되는 문제였다. 나는 일단 코드가 길어지는 과정에서 계속 실수도 났고 문제 자체가 어렵게 느껴져 결국 해설을 본 문제.
- 몇 분? 2시간 30분
1. 택시의 위치를 시작점으로 지정
2. 이동마다, 손님이 있는 곳 혹은 목적이에 도착할 때 나온 이동 거리로 남은 연료 계산
3. 택시와 가장 가까운 손님 거리를 구하기 위한 BFS 활용
4. 우선순위 큐에 택시와 손님 사이의 결과로 [이동 거리, 행, 열, 위치 정보 인덱스] 형식으로 삽입(연료가 존재하고, 이동 가능할 경우에만 실행)
5. 목적지에 도착하면 이동한 거리 x2만큼 연료 충전
이 문제의 포인트는 bfs의 활용에 대한 생각을 해냈는지와 그 구현 능력, 긴 코드의 구현 능력이 중요했다고 생각한다. 코드가 길어져 잘 못 푸는 모습에 속상하지만 더 노력해야겠다.
이 문제는 서로 대칭하는 가장 짧은 문자열을 만들기 위한 것으로, 브루트 포스를 활용해 풀었다.
- 몇 분? 2시간
1. 문자열을 리스트로 받아 처음과 끝에서부터 범위를 좁혀가면서 비교하면서 팰린드롬인 부분 찾기
2. 팰린드롬이 아닌 만큼 길이를 더해줘야 팰린드롬 꼴을 만들 수 있기 때문에, 팰린드롬이 아닌 길이를 팰린드롬에 해당하는 길이에 더해줌
이 문제의 포인트는 팰린드롬의 특징을 어떻게 활용할지에 대한 부분과, 브루트 포스로 풀 생각을 할 수 있는지가 관건이었다고 생각한다.
이 문제는 아직 내가 bfs 부분이 많이 부족하다는 생각을 느끼게 해 준 문제이다. 결국 풀지 못해 해설을 본 …
=> [220118] 정하영

yhw/220118/1.java, yhw/220118/2.java, yhw/220118/3.java
`한 줄 소감을 쓰시오`
이 문제는...
- 몇 분?
1. 이 문제는...
이 문제의 포인트는...
이 문제는...
- 몇 분?
1. 이 문제는...
이 문제의 포인트는...
이 문제는...
- 몇 분?
1. 이 문제는...
이 문제의 포인트는...
=> [220118] 유한욱

jhy/220118/거울 설치.py, jhy/220118/스타트 택시.py, jhy/220118/팰린드롬 만들기.py, yhg/Palin.py, yhg/mirror.py, yhg/startTaxi.py, yhw/220118/1.java, yhw/220118/2.java, yhw/220118/3.java
`한 줄 소감을 쓰시오`
이 문제는...
- 몇 분?
1. 이 문제는...
이 문제의 포인트는...
이 문제는...
- 몇 분?
1. 이 문제는...
이 문제의 포인트는...
이 문제는...
- 몇 분?
1. 이 문제는...
이 문제의 포인트는...
=> 220118 study

yhg/passwordcode.py
`한 줄 소감을 쓰시오`
이 문제는...
- 몇 분?
1. 이 문제는...
이 문제의 포인트는...
이 문제는...
- 몇 분?
1. 이 문제는...
이 문제의 포인트는...
이 문제는...
- 몇 분?
1. 이 문제는...
이 문제의 포인트는...
=> 암호코드 - 유현근

nyc/220530/programmers_프렌즈4블록.py
`오랜만`
이 문제는 시뮬레이션 유형이고, 2차원 배열을 잘 다루면 되는 문제이다.
- 35분
1. 2차원 배열로 변환
2. 전체 탐색하며 2x2 모양이 전부 같은지 판별 -> 같다면 pop대상으로 지정(set 사용하여 중복 제거), set의 크기를 보고 pop 개수 세어주기
3. pop대상을 뭔가 특정 문자로 치환(나는 ""로 했음)
4. 빈 공간을 채워주기(아래서부터 위로 올라가면서 탐색하면 됨)
5. 2로 돌아가기, 만약 2에서 pop대상의 개수가 0이면 종료
이 문제의 포인트는 빡구현. 배열에서 index 안헷갈리게 주의하기. 이런 문제의 경우 함수를 잘게 쪼개서 푸는게 정신건강에 이롭다.
=> [220530] 남윤창

jhy/220530/프렌즈4블록.py
`2차원 배열의 빡구현과 친해질 필요가 있다!`
시뮬레이션 문제에서는 각 단계를 함수화해서 구현하는게 도움이 많이 된다.
하지만 2차원 배열의 인덱스 활용에서 버벅인 부분이 되게 크게 와닿았다.
- 4시간
1. 2x2로 같은 문자가 나오는 구역을 전부 체크해둔 후, 한번에 ''로 바꿔줌
2. 맨 밑줄에서부터 ''가 나오면 윗줄과 바꿔주는 작업 수행.
3. 최종 결과 판에서 '' 개수를 결과로 반환.
이 문제는 2차원 배열의 인덱스를 얼마나 잘 활용하는가가 핵심이었다고 생각한다.
=> [220530] 정하영

yhg/friends.py
`한 줄 소감을 쓰시오`
이 문제는...
- 몇 분?
1. 이 문제는...
이 문제의 포인트는...
이 문제는...
- 몇 분?
1. 이 문제는...
이 문제의 포인트는...
이 문제는...
- 몇 분?
1. 이 문제는...
이 문제의 포인트는...
=> [220530] 유현근

nyc/220606/programmers_순위검색.py
`드럽다`
이 문제는 5만개 정보, 10만개 쿼리가 있기 때문에 무지성 탐색하면 털린다.
뭔가 정보의 정리와 탐색의 logN이 필요하다.
해결할 수 있는 방법은, 처음 입력된 정보를 딕셔너리로 정리하고, 정리된 점수를 정렬해서 이진탐색 해야한다.
- 60분
1. dictionary로 info를 split해서 저장. 나같은 경우는 4가지 정보의 종류가 있기 때문에 이를 "1111", "1211" 등과 같이 code로 변환했음
2. dictionary 안의 리스트를 sort
3. query는 dash값이 들어오면 모든 정보를 탐색해야 하므로, code를 재조합.
4. 재조합된 code 리스트를 돌며 이진탐색해서 score이상의 값이 몇 개 인지 셈
이 문제의 포인트는, 1) 코드 짜기 전에 시간복잡도 계산을 해보았는가, 2) 드러운 구현을 얼마나 깔끔하게 해내는가
=> [220606] 남윤창
